### ISSUE TITLE
Model has no attribute model_id

### ISSUE THREAD

**Issue by ries9112** [numerai/numerai-cli#13]
Thank you for putting together such an awesome system. I followed the instructions and the youtube video and I was able to set things up correctly (I believe). However, when the code itself runs, the predict.py file gives me an error that says "AttributeError: module 'model' has no attribute 'model_id'" see screenshot below:

![numerai_error](https://user-images.githubusercontent.com/32306488/82174145-e7cc7100-988c-11ea-9f09-d679d1b12c1c.png)

Thoughts around what I'm doing wrong here? Any help would be much appreciated!

**Comment by jorijnsmit** [comment]
This doesn't appear to be an issue with `numerai-cli` but with your `predict.py` file.

**Comment by ries9112** [comment]
That is correct. I was under the impression that the example model would work as given. Are there any good examples people have published for the predict.py file for a Numerai competition?

**Comment by jorijnsmit** [comment]
If I read the source code correctly, and indeed understand correctly that you are using `predict.py` from this repo, then it looks like you have to set `model_id` yourself here: https://github.com/numerai/numerai-cli/blob/57fdb4232451126f3382311cefb2e0174c87e4bc/numerai_compute/examples/python3/model.py#L12

**Comment by jparyani** [comment]
You can get a multi-model example by running `numerai docker copy-example -m`. Alternatively, take a look at https://github.com/numerai/numerai-cli/blob/master/numerai_compute/examples/python3-multimodel/predict.py#L56 to see that you just need to add a `model_id` parameter to `nx.upload`
