### ISSUE TITLE
Terraform error

### ISSUE THREAD

**Issue by JoeBlair** [numerai/numerai-cli#17]
Hi guys, 

Im trying to set up AWS however I get this error when following the tutorial:

Error: Could not load plugin
```


Plugin reinitialization required. Please run "terraform init".

Plugins are external binaries that Terraform uses to access and manipulate
resources. The configuration provided requires plugins which can't be located,
don't satisfy the version constraints, or are otherwise incompatible.

Terraform automatically discovers provider requirements from your
configuration, including providers used in child modules. To see the
requirements and constraints, run "terraform providers".

Failed to instantiate provider "registry.terraform.io/hashicorp/aws" to obtain
schema: fork/exec
.terraform/plugins/registry.terraform.io/hashicorp/aws/3.13.0/linux_amd64/terraform-provider-aws_v3.13.0_x5:
exec format error
```

Any help would be great

**Comment by ndharasz** [comment]
@JoeBlair I'll be taking a look at this, can you remember which command caused this issue?

**Comment by ndharasz** [comment]
I'm going to close this. If you're still running into this error, please open a new ticket with the following information:
- Current OS Version (e.g. MacOS 10.9, Windows 10, Ubuntu 18.04, etc.)
- Current Platform (e.g. Macbook Pro 2018, Custom PC, think pad, etc.)
- Command you ran that caused the error (e.g. `numerai setup`, `numerai compute test-webhook`, etc.)
