### ISSUE TITLE
Key_file it's not defined in load_or_setup_keys

### ISSUE THREAD

**Issue by dvdpedros** [numerai/numerai-cli#21]
Hi! 
I think that the `load_or_setup` command is failing because the variable `key_file` is not initialized.
I've solved it by adding `get_key_file` before. Is it just me? Thanks!

**Comment by ndharasz** [comment]
I think this was fixed in the most recent release, could you update your numerai-cli package and try again?

**Comment by ndharasz** [comment]
Closing this issue because it's stale. I you encounter this error again please post the full stack trace when creating an issue.
