### ISSUE TITLE
numerai node config fails when there is already an IAM role present

### ISSUE THREAD

**Issue by simpsus** [numerai/numerai-cli#32]
setup is a blank ubuntu 20.04.
numerai setup runs without complaint. configuring a node gives

(numerai) gbrecht@desktop:~/Documents/numerai/compute-neutralblender$ numerai node config --example tournament-python3
Model name: neutralblender
Copying tournament-python3 example to tournament-python3
configuring node "numerai-neutralblender"...
running terraform to provision cloud infrastructure...
Error: Numerai CLI was unable to identify an error, please try to use the "--verbose|-v" option for more information before reporting this
module.aws[0].aws_cloudwatch_log_group.gateway: Creating...
module.aws[0].aws_apigatewayv2_api.submit: Creating...
module.aws[0].aws_ecr_repository.node["numerai-neutralblender"]: Creating...
module.aws[0].aws_vpc.main: Creating...
module.aws[0].aws_cloudwatch_log_group.lambda["numerai-neutralblender"]: Creating...
module.aws[0].aws_lambda_layer_version.node_modules: Creating...
module.aws[0].aws_iam_role.ecsTaskExecutionRole: Creating...
module.aws[0].aws_ecs_cluster.main: Creating...
module.aws[0].aws_iam_role.iam_for_lambda: Creating...
module.aws[0].aws_cloudwatch_log_group.ecs["numerai-neutralblender"]: Creating...
module.aws[0].aws_apigatewayv2_api.submit: Creation complete after 1s [id=5sbe9r6b5h]
module.aws[0].aws_ecr_repository.node["numerai-neutralblender"]: Creation complete after 1s [id=numerai-neutralblender]
module.aws[0].aws_cloudwatch_log_group.lambda["numerai-neutralblender"]: Creation complete after 2s [id=/aws/lambda/numerai-neutralblender]
module.aws[0].aws_cloudwatch_log_group.ecs["numerai-neutralblender"]: Creation complete after 2s [id=/fargate/service/numerai-neutralblender]
module.aws[0].aws_vpc.main: Creation complete after 5s [id=vpc-048f43a03d1c0d49a]
module.aws[0].aws_internet_gateway.gw: Creating...
module.aws[0].aws_security_group.ecs_tasks: Creating...
module.aws[0].aws_subnet.public[0]: Creating...
module.aws[0].aws_internet_gateway.gw: Creation complete after 3s [id=igw-0e4008402bbc9558b]
module.aws[0].aws_route.internet_access: Creating...
module.aws[0].aws_security_group.ecs_tasks: Creation complete after 4s [id=sg-09253eae4a873fbb3]
module.aws[0].aws_route.internet_access: Creation complete after 2s [id=r-rtb-022f5e944574a8c0f1080289494]
module.aws[0].aws_lambda_layer_version.node_modules: Still creating... [10s elapsed]
module.aws[0].aws_ecs_cluster.main: Still creating... [10s elapsed]
module.aws[0].aws_ecs_cluster.main: Creation complete after 11s [id=arn:aws:ecs:us-east-1:995503025700:cluster/numerai-submission]
module.aws[0].aws_lambda_layer_version.node_modules: Creation complete after 12s [id=arn:aws:lambda:us-east-1:995503025700:layer:node_modules:3]
module.aws[0].aws_subnet.public[0]: Still creating... [10s elapsed]
module.aws[0].aws_subnet.public[0]: Creation complete after 13s [id=subnet-0252b69c64bb0df8b]

Error: Error creating IAM Role numerai-submission-ecs: EntityAlreadyExists: Role with name numerai-submission-ecs already exists.
	status code: 409, request id: 4a0fa7b4-cc51-4191-95a2-979071535798

  on aws/cluster.tf line 61, in resource "aws_iam_role" "ecsTaskExecutionRole":
  61: resource "aws_iam_role" "ecsTaskExecutionRole" {

Error: Creating CloudWatch Log Group failed: ResourceAlreadyExistsException: The specified log group already exists:  The CloudWatch Log Group '/aws/apigateway/numerai-submission' already exists.

  on aws/webhook.tf line 52, in resource "aws_cloudwatch_log_group" "gateway":
  52: resource "aws_cloudwatch_log_group" "gateway" {

Error: Error creating IAM Role numerai-submission-lambda: EntityAlreadyExists: Role with name numerai-submission-lambda already exists.
	status code: 409, request id: aaade368-efa9-4680-b732-5315996315b1

  on aws/webhook.tf line 144, in resource "aws_iam_role" "iam_for_lambda":
 144: resource "aws_iam_role" "iam_for_lambda" {

**Comment by simpsus** [comment]
Maybe I am using it wrong, because setting up multiple nodes with the same IAM should not be a problem. Otherwise ... how is anyone using numerai-cli to setup multiple nodes?

**Comment by pmcbride** [comment]
I am actually running into the same issue @simpsus, how did you solve it? I am not very familiar with AWS and IAM

**Comment by simpsus** [comment]
You will not like this ... I resurrected an old email from before my marraige-induced name change and created a new AWS account.

**Comment by pmcbride** [comment]
Haha, ok great. Well it turns out I only have the problem when I want to work on my windows boot. Everything works fine in my original numerai-cli setup in ubuntu. I've tried generating new API keys for numerai and going through the AWS IAM setup again and it doesnt help
