### ISSUE TITLE
numerai: command not found

### ISSUE THREAD

**Issue by VictorOtin** [numerai/numerai-cli#52]
After pip installing numerai as stated in the repo and updated to the newest version, I got a `numerai: command not found` when I run any of the commands starting with `numerai`. For example with `numerai setup`

Anyone else also having this problem?
Any help is really appreciated ☺️

**Comment by dylanbodkin** [comment]
yes I am having a similar problem. After running the command `pip3 install numerai-cli` and then trying 
`numerai setup` i get the following error `'numerai' is not recognized as an internal or external command,
operable program or batch file.`

**Comment by davidchris** [comment]
I had the same issue and I restarted my terminal session. Maybe it wasn't picked up in PATH yet.
