### ISSUE TITLE
Error using credentials to get account ID

### ISSUE THREAD

**Issue by kumikoda** [numerai/numerai-cli#6]
A user reported this error

`Error: error using credentials to get account ID: error calling sts:GetCallerIdentity: InvalidClientTokenId: The security token included in the request is invalid.
status code: 403`

after some digging it seems like the keys in `~/.numerai` where invalid (maybe copy and paste error?). 

Anyways, we deleted the file and ran `numerai setup` again with the correct keys and it worked. 

I see that there is code that checks the validity of the keys. Perhaps it can be moved from `setup keys` into `load keys` since the keys can become invalid or corrupted in the mean time.

**Comment by kumikoda** [comment]
Perhaps we can also add a `numerai doctor` command that just checks everything and prints out good debug logs to make it easier to remotely help someone

**Comment by kumikoda** [comment]
and maybe a `numerai clean` that deletes / resets everyhing

**Comment by ndharasz** [comment]
@kumikoda do you have a list of ideas for the doctor command? I feel like that is going to be on the level of an integration test

**Comment by kumikoda** [comment]
Some basics
- is my local environment setup correctly? ie is docker running, do i have the latest version of numerai-cli etc
- is my numerai API key configuration setup correctly? does my key give me the required access to download and submit?
- is my container up and running? maybe some type of simple health check  
- and then print all this information out, and instruct the user to go to rocketchat and paste all of this debug info when asking a question
