### ISSUE TITLE
update troubleshooting guide with new cli command for adjusting memory

### ISSUE THREAD

**Issue by gosuto-inzasheru** [numerai/numerai-cli#66]
im running into out of memory issues when following the [getting started article](https://docs.numer.ai/tournament/compute#getting-started).

according to the [troubleshooting guide](https://github.com/numerai/numerai-cli/wiki/Troubleshooting#cloud-out-of-memory-issues), this can be mitigated by adjusting memory configuration:
```
numerai setup -c 4096 -m 30720
```
however:
```
Usage: numerai setup [OPTIONS]
Try 'numerai setup --help' for help.

Error: No such option: -c
```

did this flag get renamed, or deprecated? if so, how do i adjust memory config now?

ah also, i cannot find the `~/.numerai/variables.tf` mentioned.

best i could do is
```
numerai list-constants
```
```
SIZE_PRESETS:
  gen-sm -> cpus: 1.0, mem: 4.0 GB 
  gen-md -> cpus: 2.0, mem: 8.0 GB 
  gen-lg -> cpus: 4.0, mem: 16.0 GB 
  cpu-xs -> cpus: 0.5, mem: 1.0 GB 
  cpu-sm -> cpus: 1.0, mem: 2.0 GB 
  cpu-md -> cpus: 2.0, mem: 4.0 GB 
  cpu-lg -> cpus: 4.0, mem: 8.0 GB 
  mem-sm -> cpus: 1.0, mem: 8.0 GB 
  mem-md -> cpus: 2.0, mem: 16.0 GB (default)
  mem-lg -> cpus: 4.0, mem: 30.0 GB 
See https://docs.aws.amazon.com/AmazonECS/latest/developerguide/task-cpu-memory-error.html for more info about size presets.
```

all this is with `numerai-cli==0.3.4`

**Comment by gosuto-inzasheru** [comment]
solved through `numerai node config -s mem-lg`

this is not documented yet though in the docs i linked

**Comment by gosuto-inzasheru** [comment]
this might also mean there are more changes that havent been documented.

i am not sure of the scope of breaking changes and their coverage in the docs, please advice.

**Comment by ndharasz** [comment]
fixed in both the wiki and the readme.
